cameras:
- fill_mode: stretch
  id: cam_driveway
  name: Driveway
  substream: rtsp://192.168.86.233:7447/PbwGrj1UkxmoQk0F
  url: rtsp://192.168.86.233:7447/d9eh8leuMKC5718t
  use_substream: false
- fill_mode: stretch
  id: cam_frontdoor
  name: Front Door
  substream: rtsp://192.168.86.233:7447/8rFAf4Y7OUsjEHc0
  url: rtsp://192.168.86.233:7447/LqWilAyQefPYMtZw
  use_substream: false
- fill_mode: stretch
  id: cam_backyard
  name: Back Yard
  substream: rtsp://192.168.86.233:7447/XJPkRfWN4t6XPeQI
  url: rtsp://192.168.86.233:7447/eH1LEipmsDmwRX5P
  use_substream: false
- fill_mode: stretch
  id: cam_trash
  name: Trash
  substream: rtsp://192.168.86.233:7447/AkM4O6ZWS0vx23jq
  url: rtsp://192.168.86.233:7447/HInhAyRnFaGR0tc5
  use_substream: false
- fill_mode: stretch
  id: doorbellcam
  name: Door Bell
  substream: rtsp://192.168.86.233:7447/EAC08ZaUhojOLCgw
  url: rtsp://192.168.86.233:7447/KL2T8P4SrrM0AItL
  use_substream: false
- fill_mode: stretch
  id: drivewaytop
  name: Drive top view
  substream: rtsp://192.168.86.233:7447/JgCxNHmVrjrnKbOy
  url: rtsp://192.168.86.233:7447/aWRz5wBgIrCvilVe
  use_substream: false
- fill_mode: stretch
  id: frontyard
  name: Front Yard
  substream: rtsp://192.168.86.233:7447/LUlolhxFqSbRxpk8
  url: rtsp://192.168.86.233:7447/jJXGzLQ2PGw1jk3z
  use_substream: false
- fill_mode: stretch
  id: garage
  name: Garage
  substream: rtsp://192.168.86.233:7447/a5x3X1FIDyQGoBBj
  url: rtsp://192.168.86.233:7447/Y77hMpUmD2Jvn2xv
  use_substream: false
- fill_mode: stretch
  id: rickycam
  name: Ricky
  substream: rtsp://192.168.86.233:7447/FdDeUreay23q5rUO
  url: rtsp://192.168.86.233:7447/XAWR9azg6Ek0Sfhq
  use_substream: false
- fill_mode: stretch
  id: jorgitocam
  name: Jorgito
  substream: rtsp://192.168.86.233:7447/kKWWuImMfFk1ddma
  url: rtsp://192.168.86.233:7447/yVsSNP2aho4eTc5p
  use_substream: false
monitors:
- default_playlist: alldayallcameras
  id: 1
  name: Monitor 1
  schedule: []
- default_playlist: pl_night
  id: 2
  name: Monitor 2
  schedule: []
playlists:
- id: pl_business
  name: Business Hours
  rotation:
  - cameras:
    - cam_driveway
    duration: 5
    layout: 1
    name: Driveway
  - cameras:
    - cam_driveway
    - cam_frontdoor
    - cam_backyard
    - cam_trash
    duration: 10
    layout: 4
    name: Quad View
  - cameras:
    - cam_frontdoor
    duration: 5
    layout: 1
    name: Front Door
  - cameras:
    - cam_driveway
    - cam_backyard
    - rickycam
    - jorgitocam
    - drivewaytop
    - doorbellcam
    - garage
    duration: 5
    layout: 3L4S
    name: Back Yard
  - cameras:
    - cam_driveway
    - cam_frontdoor
    - cam_backyard
    - cam_trash
    duration: 30
    layout: 4
    name: Quad View Long
  - cameras:
    - cam_trash
    duration: 5
    layout: 1
    name: Trash
  - cameras:
    - doorbellcam
    duration: 10
    layout: 1
    name: DoorBell
- id: pl_night
  name: Night Mode
  rotation:
  - cameras:
    - drivewaytop
    - frontyard
    - rickycam
    - garage
    - doorbellcam
    - jorgitocam
    duration: 0
    layout: 6
    name: All Cameras
- id: alldayallcameras
  name: All cámaras all day
  rotation:
  - cameras:
    - cam_driveway
    - cam_frontdoor
    - cam_backyard
    - cam_trash
    - doorbellcam
    - drivewaytop
    - frontyard
    - garage
    - rickycam
    duration: 0
    layout: 9
    name: All cameras
system:
  admin_password_hash: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
  alert_email_from: ''
  alert_email_to: ''
  debug_log: false
  gmail_app_password: ''
  watchdog_interval: 30
