system:
  admin_password_hash: b9de7cc6daa8581a6785f9b6d1a7a23c544d07977035a95998c8f1daf9227639
  alert_email_from: ''
  alert_email_to: ''
  gmail_app_password: ''
  watchdog_interval: 30
cameras: []
playlists: []
monitors:
- id: 1
  name: Monitor 1
  x: 0
  y: 0
  w: 1920
  h: 1080
  schedule: []
setup_mode: true
